### ISSUE TITLE
could be a chrome issue on my end but the dropdowns are buggy as hell. (see gif)

### ISSUE THREAD

**Issue by CameronWeller** [betaflight/firmware-presets#183]
![betaflight-configurator_aHXDz6Z957](https://user-images.githubusercontent.com/20343009/153734990-b133ecb2-4e34-41dc-a2c8-e508c30a70fc.gif)

**Comment by limonspb** [comment]
I bet you are using RC1 or RC2 or something earlier.

There are several problems here with several answers:
1. Options list inside the presets doesn't show correctly, and can't pick a preset.
Solution: Update to the latest nightly configurator or to RC3

2. Keywords dropdown scroll does not work - [known issue](https://github.com/betaflight/betaflight-configurator/issues/2789)
Solution: Update to the latest nightly

Let me know if i missed anything else.
