### ISSUE TITLE
Remarks about RC Link /50 Hz ELRS Preset

### ISSUE THREAD

**Issue by LoakAudio** [betaflight/firmware-presets#190]
Hi,

2 things about 50Hz ELRS preset :
- in RC Link, the chosen Serial Rx Provider is CRSF, may be a source of error if you have a spi ELRS RX
- In RC Link, If cinematic option is chosen, a 25 stronger jitter factor is added but 20 seems to be the max.

**Comment by ctzsnooze** [comment]
Thanks
Good points.
Please see https://github.com/betaflight/firmware-presets/pull/191
