### ISSUE TITLE
Add presets for ELRS 915MHz @ 200Hz control link?

### ISSUE THREAD

**Issue by ApolloBian** [betaflight/firmware-presets#198]
Currently there is only preset for ELRS 50Hz/150Hz/250Hz/500Hzcontrol link. However, ELRS 915MHz runs at 200Hz, which isn't covered by any available presets.

Here I post my flyable settings for ELRS 200Hz. However, I'm far from a good tuner to produce perfect results. I wish ELRS@200Hz can be officially covered.

My settings for ELRS 200Hz:
```
# Feedforward
feedforward_averaging = 2_POINT
feedforward_smooth_factor = 65
feedforward_jitter_factor = 12
feedforward_boost = 5

# RC Smoothing
rc_smoothing = ON
rc_smoothing_auto_factor = 30
rc_smoothing_auto_factor_throttle = 30

```

**Comment by limonspb** [comment]
Hey!

Could you please apply your settings, take props off (or don't even power the motors) and do the following, recording blackbox:

Can be desk logs with smooth stick moves, sinusoidal like, start slow, like 0.5hz, get faster and faster.  I stay inside one half of the range and avoid hitting centre or limits.
Then some ‘imaginary’ flips or rolls.  and some ‘pretend flying’.
log to the debug ff_interpolated  = feedforward.

After that plz share your blackbox here. Maybe there are some parameters to tweak.
Thanks!

**Comment by Fumes74** [comment]
[logs.zip](https://github.com/betaflight/firmware-presets/files/8237499/logs.zip)
I have done the requested exercise above.
RM TX16S - EDGETX 2.6 - Max bauds 1.87M - ADC filter off
ELRS 2.3 - 900MHz / 200HZ on R9M TX and R9MM RX
BF 4.3 RC3 - logged debug to FEEDFORWARD

I could probably do more testing if these logs does not meet the expectations.

**Comment by Fumes74** [comment]
[logs.zip](https://github.com/betaflight/firmware-presets/files/8237927/logs.zip)

I have done the requested exercise above.

RM TX16S - EDGETX 2.6 - Max bauds 1.87M - ADC filter off
ELRS 2.3 - 900MHz / 200HZ on R9M TX and R9MM RX
BF 4.3 RC3 - logged debug to FEEDFORWARD

All logs are on bench with motors off so i don't know really how well the logs actually compares to a real flight.
I could probably do more testing if these logs does not meet the expectations.

**Comment by limonspb** [comment]
> [logs.zip](https://github.com/betaflight/firmware-presets/files/8237927/logs.zip)
> 
> I have done the requested exercise above.
> 
> RM TX16S - EDGETX 2.6 - Max bauds 1.87M - ADC filter off ELRS 2.3 - 900MHz / 200HZ on R9M TX and R9MM RX BF 4.3 RC3 - logged debug to FEEDFORWARD
> 
> All logs are on bench with motors off so i don't know really how well the logs actually compares to a real flight. I could probably do more testing if these logs does not meet the expectations.

Thank you Sir!
@ctzsnooze @spatzengr @sugaarK could you please have a look?

**Comment by ApolloBian** [comment]
@limonspb sorry for the delay, here is my test results:
[LOG038.TXT](https://github.com/betaflight/firmware-presets/files/8239292/LOG038.TXT)

Also, @Fumes74 thank you

**Comment by sugaarK** [comment]
just had a look @ApolloBian... make some new logs with full stick inputs left to right in increasing speed..
make the ff smoothing 45 and turn off the averaging.. its over smoothed and over averaged right now

**Comment by ApolloBian** [comment]
@sugaarK
[LOG040.TXT](https://github.com/betaflight/firmware-presets/files/8239430/LOG040.TXT)
feedforward_averaging = OFF, feedforward_smooth_factor = 45 as suggested

**Comment by sugaarK** [comment]
ok so it needs averaging but you need to put the boost back to 15 and leave the jitter at stock.. to make a preset things kinda need to start from stock not from settings that are effecting the situation. if you can do that then we can try another log.. bench testing is fine

**Comment by limonspb** [comment]
@ApolloBian  :)

**Comment by ApolloBian** [comment]
Hey boys, I've been out on a business trip(Didn't bring quads with me). Due to quarantine I cannot provide any feedbacks recently, sorry for that :-(

**Comment by limonspb** [comment]
> Hey boys, I've been out on a business trip(Didn't bring quads with me). Due to quarantine I cannot provide any feedbacks recently, sorry for that :-(

No worries.
Whenever you got time. Or maybe @Fumes74 can follow up :)

**Comment by Fumes74** [comment]
@limonspb @sugaarK
Can I have the settings that you want pasted here, so that i have exactly right prerequisites?
Then it should be no problem for me to do some testing.

The stick input can be from one stick only and full deflection left to right?

**Comment by sugaarK** [comment]
Surr thing I can tell you now or wait until I finish work for a cli snippet.. 

Start with stock FF and rc settings. 
Then we want ff smoothing set to 45 and averaging set to 2_point.. also test ff smoo set to 35. One stick it fine say just roll. I like to do full left to right movements that start fast and get slower and slower

**Comment by sugaarK** [comment]
try this.. make sure the other rc settings are STOCK.. @ApolloBian's logs were not with stock settings so hard to get a good gauge.. 

roll stick inputs is fine...  

set feedforward_averaging = 2_POINT
set feedforward_smooth_factor = 45 

and try 

set feedforward_averaging = 2_POINT
set feedforward_smooth_factor = 35

**Comment by Fumes74** [comment]
[logs.zip](https://github.com/betaflight/firmware-presets/files/8322718/logs.zip)
Thank you.
I have made the exercise above.
Attached are 3 logs with appropiate naming.

**Comment by Fumes74** [comment]
@limonspb @limonspb 
Did the logs work out or do we need more?

**Comment by limonspb** [comment]
> @limonspb @limonspb Did the logs work out or do we need more?

sorry for the delay.
I am not very familiar with these settings, trying to poke @sugaarK as much as i can

**Comment by sugaarK** [comment]
35 looks good but you still have the boost 30% lower than stock it should be 15.. so at slower stick inputs your not getting much ff.. I think the settings are solid though.... if you wana put up the ff boost to 15 and try the 2 tests again.. its looking though as I said too @limonspb  privately much the same as 250hz...

**Comment by limonspb** [comment]
250Hz preset works good with 200Hz link.
