### ISSUE TITLE
Information in default file is simply wrong and misleading

### ISSUE THREAD

**Issue by Quick-Flash** [betaflight/firmware-presets#225]
![image](https://user-images.githubusercontent.com/46289813/159424027-3c54d862-3d33-4bb6-bf1f-8609388b3157.png)
Here the Karate preset shows some wrong information. Integrated yaw is being confused for FPV Camera Angle. Integrated yaw does not mix roll and pitch, integrated yaw literally integrates the yaw pidsum.

Wrong information like this in presets will only add to user confusion and should be fixed.

**Comment by sugaarK** [comment]
Where is this information.. I wrote the karate preset and this is not in it.. integrated yaw Should be set to OFF unless you have some idea of how it works and there are very few people who do....

**Comment by Quick-Flash** [comment]
> lols This is in the Default file not the karate tune exclusively. If you look properly you’ll find it’s in all the tunes when you look at the whole diff that uses the default files... come on man your way better at this Git stuff than this... I wrote the karate preset and this is not in it.. integrated yaw Should be set to OFF unless you have some idea of how it works and there are very few people who do.... 😉

Did not realize it was in all tune presets, that makes the issue even worse. Yes I'd agree that integrated yaw should be turned off by default unless you know what your doing, but that doesn't change the fact that the default file is confusing integrated yaw for FPV camera angle. The default preset file tells users that integrated yaw is actually FPV camera angle, which could lead to users setting it up thinking that it will mix pitch and yaw, or yaw and roll, to help coordinate turns. Integrated yaw does not help with coordinated turns, its simply a different way to calculate the pidsum on yaw.

**Comment by limonspb** [comment]
> > lols This is in the Default file not the karate tune exclusively. If you look properly you’ll find it’s in all the tunes when you look at the whole diff that uses the default files... come on man your way better at this Git stuff than this... I wrote the karate preset and this is not in it.. integrated yaw Should be set to OFF unless you have some idea of how it works and there are very few people who do.... 😉
> 
> Did not realize it was in all tune presets, that makes the issue even worse. Yes I'd agree that integrated yaw should be turned off by default unless you know what your doing, but that doesn't change the fact that the default file is confusing integrated yaw for FPV camera angle. The default preset file tells users that integrated yaw is actually FPV camera angle, which could lead to users setting it up thinking that it will mix pitch and yaw, or yaw and roll, to help coordinate turns. Integrated yaw does not help with coordinated turns, its simply a different way to calculate the pidsum on yaw.

Thanks for the finding. Easy fix, can just remove that comment.
I would not dramatize this. Because that's just a comment in the CLI snippet that regular users never see. Unless they check raw CLI. Such comments do not go anywhere in the description. But it would be nice to still fix it. Could you make a pr for removing? Or i can no problem.

**Comment by Quick-Flash** [comment]
> Thanks for the finding. Easy fix, can just remove that comment. I would not dramatize this. Because that's just a comment in the CLI snippet that regular users never see. Unless they scroll through the raw CLI blanket. Regular comments `#` do not go anywhere in the `#$` description. But it would be nice to still fix it. Could you make a pr for removing? Or i can no problem.

I can make a PR later. I guess I'm not a regular user if I read the cli snippet its going to apply, haha.

**Comment by sugaarK** [comment]
@Quick-Flash  you won’t see it either if you use the read on line button as it only brings up the presets cli snippet not all the included stuff

**Comment by limonspb** [comment]
> > Thanks for the finding. Easy fix, can just remove that comment. I would not dramatize this. Because that's just a comment in the CLI snippet that regular users never see. Unless they scroll through the raw CLI blanket. Regular comments `#` do not go anywhere in the `#$` description. But it would be nice to still fix it. Could you make a pr for removing? Or i can no problem.
> 
> I can make a PR later. I guess I'm not a regular user if I read the cli snippet its going to apply, haha.

Yeah these are quite big cuz they also show all the included files at the begining.
