### ISSUE TITLE
Presets don't work on subsequent RC versions

### ISSUE THREAD

**Issue by antoni9** [betaflight/firmware-presets#244]
Presets don't work on subsequent RC versions - tried Karate on RC 2-3-6-7 on Foxeer stack 60A + 533 2070kv + 51466/51466v2 frames used: 533SBpro and my own custom frame, was getting a strange mid-corner high-P-sounding oscillation, happened on hard cornering when blipping throttle / on the second part of the blip [throttle increase]. At first didn't use blackbox and tried different settings, incl. motor timing - burned one motor when timing was set to 31, burned another one when ever-so-sligthly clipping a gate. 

Using blackbox, there's something in the preset that's causing the inside back motor to max out in this scenario, tried to return yaw motors reversed to normal and the issue went away. Then tried to reverse yaw and stock BF tune - the issue isn't present.
<img width="1194" alt="Screen Shot 2022-06-06 at 11 29 53" src="https://user-images.githubusercontent.com/36735931/172125109-0eff7245-8cca-4ddc-b4af-19038b274b0b.png">
[BTFL_BLACKBOX_LOG_20220604_172755.BBL.zip](https://github.com/betaflight/firmware-presets/files/8842965/BTFL_BLACKBOX_LOG_20220604_172755.BBL.zip)

**Comment by limonspb** [comment]
That's a hell of a title...
Sounds like ALL presets don't work :)

I haven't flown new 533 motors yet, but i've heard many times they just require a different tune than Karate race.

**Comment by antoni9** [comment]
Just wanted something catchy :) Will close it.

What is that stepped line in your scr?

**Comment by limonspb** [comment]
> Just wanted something catchy :) Will close it.
> 
> What is that stepped line in your scr?

battery voltage.
Github is not a youtube or reddit, people around here don't appreciate click baits

**Comment by antoni9** [comment]
Got it :)

Thanks for the info!
