### ISSUE TITLE
BMI 270 presets are confusing users. Update or remove them.

### ISSUE THREAD

**Issue by rochford77** [betaflight/firmware-presets#279]
I understand the proper place for this discussion is on the respective PRs but unfortunately the original author has blocked me for simply bringing up the issue, and I cannot comment on their PRs.

The bmi270 presets by dusking were created before we made the decision to have OSR4 be the default in betaflight.

Every day, I see posts on various socials confused about what they should do, and what they need to flash. The problem is users have the impression that the BMI270 by default needs exotic software filtering, which is no longer the case in betaflight.

This isn't meant to be a discussion about what mode is best, that has already been decided as OSR4 is currently the default. However, one of the main reasons in support of OSR4 being the default was to give users a seemless experience across different gyro platforms, and increase ease of use, which isn't being fully accomplished with the existence of these presets.

I think *one* of the following actions would help clear up confusion for users

- rename the presets to something like "Duskings Alternative Cutoff BMI 270 filters" or "Duskings Advanced BMI 270 filters" or "Duskings extreme BMI 270 filters" and an update to the preset description explaining what the preset is actually doing (moving the internal cutoff up and applying additional filtering in betaflight, and why that is beneficial) so that it's clear to users that they don't NEED the preset (at least in the same way they NEED to be flashing something like an RC link preset) but that it provides value on top of what the defaults are.

- make the preset a 4.2 preset, as a user *would* "NEED" the additional filtering on older firmwares (but remove the change in hardware mode as that wouldn't be an option on legacy firmware)

- remove the presets entirely, but I don't think that is necessarily the best option the more I think about it.

**Comment by rochford77** [comment]
The PRs in question are

https://github.com/betaflight/firmware-presets/pull/141

https://github.com/betaflight/firmware-presets/pull/182

**Comment by limonspb** [comment]
I'm for option N1, renaming it to something like... Idk to what but something that tells user. And of course adding more to description is good.

Option N2 - mark as 4.2, this can't be done because in 4.2 we didn't have a BMI support.

Option 3 - I think some people still might find it interesting to try non-osr mode. I haven't done it myself yet but planning :)

**Comment by SupaflyFPV** [comment]
thanks for the comment Ryan, I agree with you. I think if we feature this preset we should update it.

**Comment by DusKing1** [comment]
Maybe i blocked wrong users as i have received some spam on my other repos. 

But the name for that is already "DusKing's BMI270 filter settings", IDK what you are complaining.

**Comment by SupaflyFPV** [comment]
> Maybe i blocked wrong users as i have received some spam on my other repos.
> 
> But the name for that is already "DusKing's BMI270 filter settings", IDK what you are complaining.

I think it is confusing as users do not understand whether they need to select this preset or not...

Would you consider adjusting the preset to use the Betaflight filter defaults, with the Gyro Low Pass Filter slider instead of the PT2/PT3? It would make more sense...the gyro low pass slider can be changed to eg 0.5 and then the user could adjust if necessary...

**Comment by DusKing1** [comment]
> > Maybe i blocked wrong users as i have received some spam on my other repos.
> > But the name for that is already "DusKing's BMI270 filter settings", IDK what you are complaining.
> 
> I think it is confusing as users do not understand whether they need to select this preset or not...
> 
> Would you consider adjusting the preset to use the Betaflight filter defaults, with the Gyro Low Pass Filter slider instead of the PT2/PT3? It would make more sense...the gyro low pass slider can be changed to eg 0.5 and then the user could adjust if necessary...

It would be great if just adding an "Advanced"/"Extreme" would change the user's misconception (if it exists), however the fact is that the preset already has the "DusKing's" prefix, but according to the above statement, this does not change the so-called "user misconception".

No I wouldn't do it, a single static PT2/PT3 is enough. The default dynamic low pass will only mess up the final signal performance of the BMI270 in performance mode (according to the datasheet).

**Comment by sugaarK** [comment]
The users should be able and I tell the difference between experimental and offical presets with the coloured flags that the presets have but even somthing as obvious as that goes over so many peoples heads!! 
@DusKing1  maybe make it clear in the description that this is not suitable for the osr4 mode which is now stock in bf 4.3 where the bmi270 gyros can be run with more traditional filtering…

**Comment by DusKing1** [comment]
@sugaarK please just check the preset in the latest master rather the links @rochford77 provided, they have the description as `This preset also changes DLPF cutoff of BMI270 to 751Hz to provide the lowest latency.`

**Comment by rochford77** [comment]
@sugaarK I understand that was the intent of the official/community/experimental flags, but people are still posting because they are confused. This is probably due to the preset being basically *necessary* while in experimental status before OSR4 was the default, combined with the popularity of the 4.3 pre-release stage.

@DusKing1 I'm looking at the preset in the configurator right now and all I see for a description is:

>These settings are for BMI270 gyroscope only. With only these settings, the BMI270 will give a nice output and control performance. Please check the available options in this preset.

The text you are talking about is listed in the *warning*, people aren't getting that far before going on Facebook/discord and asking how to proceed. Maybe moving that verbiage to the description and making it "Duskings Advanced BMI270 filters", along with the already included "experimental" flag will make things a bit more clear.

Also, I'm not trying to "complain" I'm trying to help lower the number of questions in the community in regard to this preset.

**Comment by sugaarK** [comment]
ive removed them

**Comment by haslinghuis** [comment]
Fixed in https://github.com/betaflight/firmware-presets/pull/329
