### ISSUE TITLE
Do you want to test this code? Here you have an automated build:

### ISSUE THREAD

**Issue by larry415** [betaflight/firmware-presets#316]
Do you want to test this code? Here you have an automated build:
[Betaflight-Configurator-Android](https://github.com/betaflight/betaflight-configurator/suites/8759217070/artifacts/397085405)
[Betaflight-Configurator-Linux](https://github.com/betaflight/betaflight-configurator/suites/8759217070/artifacts/397085406)
[Betaflight-Configurator-macOS](https://github.com/betaflight/betaflight-configurator/suites/8759217070/artifacts/397085407)
[Betaflight-Configurator-Windows](https://github.com/betaflight/betaflight-configurator/suites/8759217070/artifacts/397085408)
WARNING: It may be unstable and result in corrupted configurations or data loss. Use only for testing!

_Originally posted by @github-actions[bot] in https://github.com/betaflight/betaflight-configurator/issues/3045#issuecomment-1277790011_

**Comment by limonspb** [comment]
hmmmmm? ...
