### ISSUE TITLE
SpeedyBee VTX800 VTX Table

### ISSUE THREAD

**Issue by Reywas62** [betaflight/firmware-presets#386]
The labels and values for the 600mW and 800mW are incorrect.

Is:

vtxtable powervalues 25 200 400 600 600
vtxtable powerlabels 25 200 400 800 800

Should be:

vtxtable powervalues 25 200 400 600 800
vtxtable powerlabels 25 200 400 600 800

**Comment by haslinghuis** [comment]
IIRC it's supposed to be that way.

**Comment by Reywas62** [comment]
So 800mW is supposed to be labeled as 600mW?

**Comment by haslinghuis** [comment]
![image](https://user-images.githubusercontent.com/8344830/233216645-c94a0198-d674-4317-961c-99792c944c73.png)

https://oscarliang.com/speedybee-tx800/
