### ISSUE TITLE
Betaflight Indexer NPM package

### ISSUE THREAD

**Issue by gebeto** [betaflight/firmware-presets#403]
I've extracted `indexer` to separate project: [https://github.com/gebeto/betaflight-indexer](https://github.com/gebeto/betaflight-indexer) to be able to run own Betaflight Source without doing fork of official source.

Now I just need to install `betaflight-indexer` package globally with `yarn` or `npm`, and just simply run `betaflight-indexer` command inside my own source folder

Can we make this officially?

Or we can also add `"version"` to `package.json` in this project, and then I'll be able to install this repo as dependency in my `betaflight-indexer` and use your sources of `indexer` instead of copy-pasting it to my package

**Comment by limonspb** [comment]
Not sure what's the issue of cloning presets repository. If no BF presets are needed, can just remove the whole folder.
Presets without indexer are useless, indexer is useless without presets.
Btw, besides indexer, it also needs check.js as a separate command.

The good thing about having js with presets:
1. easier to update the JS code and verify it right away.
2. In the case of JS code updates + preset syntax updates:  it will come all together, no need to worry about "what version of indexer I need for this or that preset source"

I think if we decide to move with npm, it needs to be under Betaflight/presets-indexer.
