### ISSUE TITLE
Wrong value for max power in "TBS Unify Pro32 Nano - SA 2.1" preset

### ISSUE THREAD

**Issue by martin-korinek-1985** [betaflight/firmware-presets#414]
"TBS Unify Pro32 Nano - SA 2.1" preset's Note 1. Max power set to 36db...
https://api.betaflight.com/firmware-presets/presets/4.3/vtx/Unify_Pro32_Nano_SA2_1.txt
Actual value is 28 instead of 36:
vtxtable powervalues 14 20 26 28

TBS source: https://www.team-blacksheep.com/vtx-table-for-betaflight.txt
//TBS Unify Pro32 Nano - SA 2.1
//max power set to 36db as it wil lforce the vtx to ouput max power
vtxtable powervalues 14 20 26 36

From these information I think the 36 is the correct value, but "TBS Unify Pro32 Nano - SA 2.1" preset does not provide it.
**Correct powervalues should be:
vtxtable powervalues 14 20 26 36**

**Comment by sugaarK** [comment]
this preset was made a long time ago so it could be from before they made increased the power output

**Comment by sugaarK** [comment]
see https://github.com/betaflight/firmware-presets/pull/415
