### ISSUE TITLE
Convert DJI_FPV-WTF_MSP-OSD to 4.5 Preset

### ISSUE THREAD

**Issue by Canaill51** [betaflight/firmware-presets#436]
Hi Guys,
Could it be possible to migrate https://github.com/betaflight/firmware-presets/blob/master/presets/4.4/vtx/DJI_FPV-WTF_MSP-OSD.txt

To 4.5 Vtx Preset also?

@limonspb can you help, if you are not too lazy, please? :)

Thanks in advance!

**Comment by limonspb** [comment]
@sugaarK are there any difference for DJI MSP between 4.4 and 4.5?

**Comment by sugaarK** [comment]
No not dji

**Comment by sugaarK** [comment]
Done
